### PR TITLE
Fix ruff issues

### LINKED ISSUE #54: Run soma-base through ruff and fix all reported issues?

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Fixes #54.

### CODE REVIEW

**Comment by denisri** [comment]
For my personal culture, can anyone tell me why black or ruff forbids to use `l` as a variable name, while it allows any other single letter ?

**Comment by sapetnioc** [comment]
I think that is because `l` and `1` are too similar (depending on the font used).

**Comment by denisri** [comment]
They should forbid the figure `1` also ;)

**Comment by DimitriPapadopoulos** [comment]
Not at all. If you see `1`, you know it has to be `1` because `l` is forbidden.

**Comment by denisri** [comment]
But we are *modern*, we have :fire:**syntax highlighting**:fire:

**Pull request merged**
