### PR TITLE
Merge master to 6.0

### PR DESCRIPTION
**Pull request by sapetnioc**
I create this PR to be able to check the differences when merging master into 6.0 with GitHub interface.

### CODE REVIEW

**Comment by denisri** [comment]
Conflicts seem to have been fixed ?
But, some important files have been removed, like `info.py` or `controller.py` ? Why ?

**Comment by sapetnioc** [comment]
Yes, I noticed. I made a mistake when resolving conflicts ! These files are
supposed to be the version of the 6.0 branch, I did not fixed that yet, but
I will.

**Review by sapetnioc — COMMENTED** [review]
For me it is ok now. Capsul 3.0 and soma-base tests are passing locally with this PR.

**Comment by denisri** [comment]
OK then.

**Pull request merged**
